import type { Metadata } from "next";
import { Geist, Geist_Mono, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/Navbar";
import { Footer } from "@/components/Footer";
import { StoreProvider } from "@/helpers/storeProvider";
// import { getInitialData} from "@/helpers/getInitialData";
import dbConnect from "@/lib/dbConnect";
import { ClientProvider } from "@/helpers/QueryClient";
import { cn } from "@/lib/utils";

const jetbrainsMono = JetBrains_Mono({ subsets: ['latin'], variable: '--font-mono' });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  await dbConnect();
  // const data = await getInitialData();
  return (
    <html lang="en" suppressHydrationWarning={true} className={cn("font-mono dark", "font-mono", jetbrainsMono.variable)}>
      <body className={` ${geistMono.variable} antialiased `}>
        <ClientProvider>
          <StoreProvider>
            {/* <Navbar initialUser={data} /> */}
            <Navbar />
            {children}
            <Footer />
          </StoreProvider>
        </ClientProvider>
      </body>
    </html>
  );
}

